spring.application.name=reportservice
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/rsc?ApplicationName=REPORTER??characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.root=info
server.port=7070
spring.http.converters.preferred-json-mapper=jackson
